<?php


function simple_modal_init() {
  ctools_include('ajax');
  ctools_include('modal');
  $simple_modal = array(
    'ctools-simple-modal' => array(
      'modalSize' => array(
        'type' => 'fixed',
        'width' => 600,
        'height' => 400,
        'addWidth' => 10,
        'addHeight' => 20,
      ),
      'modalOptions' => array(
        'opacity' => .5,
        'background-color' => '#000',
      ),
      'animation' => 'fadeIn',
      'modalTheme' => 'SimpleModalContent',
      'throbber' => theme('image', array('path' => ctools_image_path('ajax-loader.gif', 'ctools_ajax_sample'), 'alt' => t('Loading...'), 'title' => t('Loading'))),
    ),
  );

  drupal_add_js($simple_modal, 'setting');
  $simple_modal_js = drupal_get_path('module', 'simple_modal') . '/js/simple-modal.js';
  drupal_add_js($simple_modal_js);

  $simple_modal_css = drupal_get_path('module', 'simple_modal') . '/css/simple-modal.css';
  drupal_add_css($simple_modal_css);

  // l(t('Open modal'), 'simple_modal/simple_modal_form', array('attributes' => array('class' => 'ctools-use-modal use-ajax')));
  $link = ctools_modal_text_button(t('Open modal'), 'simple_modal/nojs/modal', '', 'ctools-modal-ctools-simple-modal');
  /*ctools_include('plugins');*/
  drupal_set_message($link);
}
/**
* Implementation of hook_menu().
*/
function simple_modal_menu() {
  $items = array();
  
  $items['simple_modal/%ctools_js/modal'] = array(
    'title' => 'Modal dialog',
    'page callback' => 'simple_modal_popup',
    'page arguments' => array(1),
    'access callback' => TRUE,
    'type' => MENU_CALLBACK,
  );

  return $items;
}

function simple_modal_popup($js = NULL) {
  
  if(!$js) {
    return drupal_get_form('simple_modal_form');
  }

  ctools_include('modal');
  ctools_include('ajax');
  $form_state = array(
    'ajax' => TRUE,
  );

  $output = ctools_modal_form_wrapper('simple_modal_form', $form_state);
  if (!empty($form_state['executed'])) {
    // We'll just overwrite the form output if it was successful.
    $output = array();
    $output[] = ctools_modal_command_display('success', $form_state['message']);
 }
  print ajax_render($output);
  exit;
}

function simple_modal_form($form, &$form_state) {
  $form['text'] = array(
    '#type' => 'textfield',
    '#title' => t('Input'),
  );

  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Submit'),
  );

  return $form;
}

function simple_modal_form_submit(&$form, &$form_state) {
  $form_state['message'] = t('Message: %message', array('%message' => $form_state['values']['text']));
}
